// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CadastroPerfilCorretoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public void Login() {
    driver.get("http://sagapwebtestes.imd.ufrn.br:3000/saga/");
    driver.findElement(By.id("btn-form-login-local")).click();
    driver.findElement(By.id("username")).sendKeys("luiz_augusto_gerente");
    driver.findElement(By.id("password")).sendKeys("sagapadmin2024");
    driver.findElement(By.cssSelector(".mx-auto")).click();
  }
  public void AssertSucesso() {
    {
      WebDriverWait wait = new WebDriverWait(driver, 3);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div.p-toast div[data-pc-section=\"message\"] span.p-toast-summary")));
    }
    assertThat(driver.findElement(By.cssSelector("div.p-toast div[data-pc-section=\"message\"] span.p-toast-summary")).getText(), is("Modelo de perfil salvo!"));
  }
  @Test
  public void cadastroPerfilCorreto() {
    Login();
    driver.findElement(By.cssSelector("#sidebar > #sidebarAccordion #accordion-meus-modelos span")).click();
    driver.findElement(By.id("__BVID__618609___BV_tab__")).click();
    driver.findElement(By.id("dropdown-1")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) > .dropdown-item")).click();
    driver.findElement(By.cssSelector("#accordion-perfil3 .card-header > .btn > .btn-content")).click();
    driver.findElement(By.id("nomePerfil3")).sendKeys("Perfil teste certo");
    driver.findElement(By.id("quantidadeVagasPerfil3")).sendKeys("3");
    driver.findElement(By.id("quantidadeVagasCadastroReservaPerfil3")).sendKeys("0");
    driver.findElement(By.id("mediaCortePerfil3")).sendKeys("7");
    driver.findElement(By.cssSelector("#collapse-perfil3 #formatoTrabalhoPerfil")).click();
    {
      WebElement dropdown = driver.findElement(By.id("formatoTrabalhoPerfil"));
      dropdown.findElement(By.cssSelector("*[value='REMOTO']")).click();
    }
    driver.findElement(By.id("descricaoPerfil3")).sendKeys("Teste teste teste");
    driver.findElement(By.id("requisitosObrigatoriosPerfil3")).sendKeys("Teste teste teste");
    driver.findElement(By.id("requisitosDesejaveisPerfil3")).sendKeys("Teste teste teste");
    driver.findElement(By.id("formacaoNecessariaPerfil3")).sendKeys("Teste teste teste");
    driver.findElement(By.id("competenciasEsperadasPerfil3")).sendKeys("Teste teste teste");
    driver.findElement(By.cssSelector(".fa-file-arrow-up > path")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 3);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div.p-toast div[data-pc-section=\"message\"] span.p-toast-summary")));
    }
    AssertSucesso();
  }
}
